apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.github: ""
  name: dummy-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dummy-koostomize
    repoURL: https://github.com/viatcheslavmogilevsky/workflow-dispatch-ufzq657s.git
    targetRevision: release/staging
    kustomize:
      images:
      - nginx:alpine-$ARGOCD_APP_REVISION
  syncPolicy:
    automated: {}