name: Just echo

on:
  status: {}
  workflow_dispatch: {}


jobs:
  debug_trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Debug env
      env:
        DEBUG_EVENT_NAME: ${{ github.event_name }}
        DEBUG_IS_NOT_EVENT_STATUS: ${{ github.event_name != 'status' }}
        DEBUG_CURRENT_REF: ${{ github.ref }}
        DEBUG_IS_CURRENT_REF_MAIN: ${{ github.ref == 'refs/heads/main' }}
        DEBUG_CURRENT_CONTEXT: ${{ github.event.context }}
        DEBUG_DOES_CURRENT_CONTEXT_STARTWITH: ${{ startsWith(github.event.context,'continuous-delivery/') }}
        DEBUG_CURRENT_STATE: ${{ github.event.state }}
        DEBUG_IS_CURRENT_STATE_SUCCESS: ${{ github.event.state == 'success' }}
        DEBUG_RIGHT_PART: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.context,'continuous-delivery/') && github.event.state == 'success' }}
      run: |
        echo "DEBUG_EVENT_NAME: $DEBUG_EVENT_NAME"
        echo "DEBUG_IS_NOT_EVENT_STATUS: $DEBUG_IS_NOT_EVENT_STATUS"
        echo "DEBUG_CURRENT_REF: $DEBUG_CURRENT_REF"
        echo "DEBUG_IS_CURRENT_REF_MAIN: $DEBUG_IS_CURRENT_REF_MAIN"
        echo "DEBUG_CURRENT_CONTEXT: $DEBUG_CURRENT_CONTEXT"
        echo "DEBUG_DOES_CURRENT_CONTEXT_STARTWITH: $DEBUG_DOES_CURRENT_CONTEXT_STARTWITH"
        echo "DEBUG_IS_CURRENT_STATE_SUCCESS: $DEBUG_IS_CURRENT_STATE_SUCCESS"
        echo "DEBUG_RIGHT_PART: $DEBUG_RIGHT_PART"



  build:
    if: ${{ github.event_name != 'status' || (github.ref == 'refs/heads/main' && startsWith(github.event.context,'continuous-delivery/') && github.event.state == 'success') }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - name: Echo context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "Hello, this is context: $GITHUB_CONTEXT"'

