name: Just echo

on:
  status: {}
  workflow_dispatch: {}


jobs:
  debug_trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Debug env
      env:
        DEBUG_EVENT_NAME: ${{ github.event_name }}
        DEBUG_IS_NOT_EVENT_STATUS: ${{ github.event_name != 'status' }}
        DEBUG_CURRENT_BRANCHES: ${{ toJson(github.event.branches) }}
        DEBUG_IS_CURRENT_BRANCHES_CONTAINS_MAIN: ${{ contains(github.event.branches.*.name,'main') }}
        DEBUG_CURRENT_CONTEXT: ${{ github.event.context }}
        DEBUG_DOES_CURRENT_CONTEXT_STARTWITH: ${{ startsWith(github.event.context,'continuous-delivery/') }}
        DEBUG_CURRENT_STATE: ${{ github.event.state }}
        DEBUG_IS_CURRENT_STATE_SUCCESS: ${{ github.event.state == 'success' }}
        DEBUG_RIGHT_PART: ${{ contains(github.event.branches.*.name,'main') && startsWith(github.event.context,'continuous-delivery/') && github.event.state == 'success' }}
        # DEBUG_SOURCE_SHA: ${{ github.event_name == 'status' &&  github.event.sha || github.sha }}
        # DEBUG_SOURCE_AUTHOR: ${{ github.event_name == 'status' &&  github.event.sha || github. }}
        # DEBUG_TARGET_ENV: 
      run: |
        echo "DEBUG_EVENT_NAME: $DEBUG_EVENT_NAME"
        echo "DEBUG_IS_NOT_EVENT_STATUS: $DEBUG_IS_NOT_EVENT_STATUS"
        echo "DEBUG_CURRENT_BRANCHES: $DEBUG_CURRENT_BRANCHES"
        echo "DEBUG_IS_CURRENT_BRANCHES_CONTAINS_MAIN: $DEBUG_IS_CURRENT_BRANCHES_CONTAINS_MAIN"
        echo "DEBUG_CURRENT_CONTEXT: $DEBUG_CURRENT_CONTEXT"
        echo "DEBUG_DOES_CURRENT_CONTEXT_STARTWITH: $DEBUG_DOES_CURRENT_CONTEXT_STARTWITH"
        echo "DEBUG_IS_CURRENT_STATE_SUCCESS: $DEBUG_IS_CURRENT_STATE_SUCCESS"
        echo "DEBUG_RIGHT_PART: $DEBUG_RIGHT_PART"



  build:
    if: ${{ github.event_name != 'status' || (contains(github.event.branches.*.name,'main') && startsWith(github.event.context,'continuous-delivery/') && github.event.state == 'success' && startsWith(github.event.target_url,'https://example.com')) }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - name: Echo context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "Hello, this is context: $GITHUB_CONTEXT"'

