name: Just echo

on:
  status: {}
  workflow_dispatch: {}


jobs:
  build:
    if: ${{ github.event_name != "status" || (github.ref == "refs/heads/main" && startsWith(github.context,"continuous-delivery/")) }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3
    - name: Echo context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "Hello, this is context: $GITHUB_CONTEXT"'

