name: Fake deploy

on:
  workflow_dispatch:
    inputs:
      override_user:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Echo context
      id: echo_context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "Hello, this is context: $GITHUB_CONTEXT"'
    - name: Checkout code
      id: code_checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        fetch-depth: 5
        fetch-tags: true
    - name: Push prod git tag
      id: tag_push
      run: |
        git config --global user.name '${{ inputs.override_user || 'github-actions' }}'
        git config --global user.email '${{ inputs.override_user || 'github-actions' }}@users.noreply.github.com'
        git tag --annotate --force --message "${{ toJson(inputs) }}" staging_release
        git push --force --tags




    # - name: getting commit sha of main
    #   uses: octokit/request-action@v2.x
    #   id: get_sha_of_main
    #   with:
    #     route: GET /repos/${{ github.repository }}/branches/main
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: getting commit sha of develop
    #   uses: octokit/request-action@v2.x
    #   id: get_sha_of_develop
    #   with:
    #     route: GET /repos/${{ github.repository }}/branches/develop
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: echo commit sha of main
    #   id: echo_sha_of_main
    #   run: "echo 'main: ${{ fromJson(steps.get_sha_of_main.outputs.data).commit.sha }}'"
    # - name: echo commit sha of develop
    #   id: echo_sha_of_develop
    #   run: "echo 'develop: ${{ fromJson(steps.get_sha_of_develop.outputs.data).commit.sha }}'"


    # - name: getting commit statuses of commit of main
    #   uses: octokit/request-action@v2.x
    #   id: get_statuses_of_main
    #   with:
    #     route: GET /repos/${{ github.repository }}/commits/main/statuses
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: getting commit statuses of commit of develop
    #   uses: octokit/request-action@v2.x
    #   id: get_statuses_of_develop
    #   with:
    #     route: GET /repos/${{ github.repository }}/commits/develop/statuses
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: echo statuses json of main
    #   id: echo_statuses_of_main
    #   run: "echo 'statuses: main: ${{ toJson(steps.get_statuses_of_main.outputs.data) }}'"
    # - name: echo statuses json of develop
    #   id: echo_statuses_of_develop
    #   run: "echo 'statuses: develop: ${{ toJson(steps.get_statuses_of_develop.outputs.data) }}'"




