name: Unknown deploy

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: code_checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
    - name: Show the files
      id: ls_files
      run: git ls-files
